apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-splunk
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: fluentd-splunk
        type: game
    spec:
      containers:
      - name: fluentd-splunk
        image: "paulkane/fluentd-to-splunk:1.1-SNAPSHOT"
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
        args:
        - -q
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers