apiVersion: v1
kind: ReplicationController
metadata:
  name: splunk-v6.2-light
  labels:
    name: splunk
spec:
  replicas: 1
  selector:
    name: splunk
    version: v6.2-light
  template:
    metadata:
      labels:
        name: splunk
        version: v6.2-light
    spec:
      containers:
      - name: splunk
        image: outcoldman/splunk:6.2-light
        ports:
        - containerPort: 8000
        - containerPort: 9997
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
